<?php 

/**
 * Baseline.
 *
 * WARNING: This file is part of the core Baseline Wordpress Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Baseline
 * @author  Last Run Media
 * @link    https://lastrunmedia.com/wordpress/
 */


 get_header(); ?>

 <main role="main">

    <div id="post-404"  class="container page-content">
      <div class="row">
        
        <div class="col-md-12">
        	<h1><?php _e( 'Whoops! Page not found.', 'baseline' ); ?></h1>
        	<h2>
					<a href="<?php echo home_url(); ?>"><?php _e( 'Return home?', 'baseline' ); ?></a>
				</h2>
        </div>


<?php get_footer(); ?>
