<?php 

/**
 * Baseline.
 *
 * WARNING: This file is part of the core Baseline Wordpress Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Baseline
 * @author  Last Run Media
 * @link    https://lastrunmedia.com/wordpress/
 */


 get_header(); ?>

 <main role="main">


    <div class="container page-content">
      <div class="row">
        
        <div class="col-md-12">
          <?php if (have_posts()): the_post(); ?>

					<h1><?php _e( 'Articles Written by ', 'baseline' ); echo get_the_author(); ?></h1>

					<?php if ( get_the_author_meta('description')) : ?>

					<?php echo get_avatar(get_the_author_meta('user_email')); ?>

					<h2><?php _e( 'About ', 'baseline' ); echo get_the_author() ; ?></h2>

					<?php echo wpautop( get_the_author_meta('description') ); ?>

					<?php endif; ?>
        </div>

      </div>

      <div class="col-md-4">

      	<?php rewind_posts(); while (have_posts()) : the_post(); ?>

			<!-- article -->
			<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>

				<!-- post thumbnail -->
				<?php if ( has_post_thumbnail()) : // Check if Thumbnail exists ?>
					<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
						<?php the_post_thumbnail(array(120,120)); // Declare pixel size you need inside the array ?>
					</a>
				<?php endif; ?>
				<!-- /post thumbnail -->

				<!-- Begin Post title -->
				<h2>
					<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>
				</h2>
				<!-- End Post Title -->

				<!-- post details -->
				<span class="date"><?php the_time('F j, Y'); ?> <?php the_time('g:i a'); ?></span>
				<span class="author"><?php _e( 'Published by', 'baseline' ); ?> <?php the_author_posts_link(); ?></span>
				<span class="comments"><?php comments_popup_link( __( 'Leave your thoughts', 'baseline' ), __( '1 Comment', 'baseline' ), __( '% Comments', 'baseline' )); ?></span>
				<!-- /post details -->

				<?php baselinewp_excerpt('baselinewp_index'); // Build your custom callback length in functions.php ?>

				<br class="clear">

				<?php edit_post_link(); ?>

			</article>
			<!-- /article -->

		<?php endwhile; ?>

		<?php else: ?>

			<!-- article -->
			<article>

				<h2><?php _e( 'Sorry, nothing to display.', 'baseline' ); ?></h2>

			</article>
			<!-- /article -->

		<?php endif; ?>

      </div>

      <div class="col-md-12">
      	<?php get_template_part('pagination'); ?>
      </div>
      
		</div>
	</main>

<?php get_footer(); ?>
