<!--
 * Baseline.
 *
 * WARNING: This file is part of the core Baseline Wordpress Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Baseline
 * @author  Last Run Media
 * @link    https://lastrunmedia.com/wordpress/
 *
 -->

<?php if (have_posts()): while (have_posts()) : the_post(); ?>

	<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>

		<!-- Begin Post Thumbnail -->
		<?php if ( has_post_thumbnail()) : // Check if thumbnail exists ?>
			<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
				<?php the_post_thumbnail(array(120,120)); // Declare pixel size you need inside the array ?>
			</a>
		<?php endif; ?>
		<!-- End Post Thumbnail -->

		<!-- Begin Post Title -->
		<h2>
			<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>
		</h2>
		<!-- End Post Title -->

		<!-- Begin Post Meta -->
		<span class="author"><?php _e( 'Written by', 'baseline' ); ?> <?php the_author_posts_link(); ?></span>
		<span class="date">on <?php the_time('F j, Y'); ?></span>
		<!-- End Post Meta -->

		<?php baselinewp_excerpt('baselinewp_index'); // Build custom callback length in functions.php ?>

		<?php edit_post_link( __( 'Edit', 'textdomain' ), '<p>', '</p>', null, 'edit-post-link' ) ?>

	</article>

<?php endwhile; ?>

<?php else: ?>

	<article>
		<h2><?php _e( 'Sorry, nothing to display.', 'baseline' ); ?></h2>
	</article>

<?php endif; ?>
