<!--
 * Baseline.
 *
 * WARNING: This file is part of the core Baseline Wordpress Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Baseline
 * @author  Last Run Media
 * @link    https://lastrunmedia.com/wordpress/
 *
 -->

<!-- Begin Pagination -->
<div class="pagination">
	<?php baselinewp_pagination(); ?>
</div>
<!-- End Pagination -->
